name: Development Build

on:
  push:
    branches:
      - 'dev'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  create-dev-build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45
    
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: node/package-lock.json
          
      - name: Install dependencies
        working-directory: ./node
        run: npm ci
        timeout-minutes: 10
        
      - name: Lint Code
        working-directory: ./node
        run: npm run lint
        timeout-minutes: 5

      - name: Run Unit Tests
        working-directory: ./node
        run: npm run test:unit
        timeout-minutes: 10

      - name: Build Vite Application (Safe)
        working-directory: ./node
        env:
          VITE_REPLICACHE_LICENSE_KEY: ${{ secrets.VITE_REPLICACHE_LICENSE_KEY }}
          VITE_APP_MDP: ${{ secrets.VITE_APP_MDP }}
        run: npm run build:safe
        timeout-minutes: 10

      - name: Make Distributables
        working-directory: ./node
        run: npx electron-forge make
        timeout-minutes: 15

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dev-build-${{ matrix.os }}
          path: node/out/make/
          retention-days: 7