name: Release Electron App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45 # Generous timeout for the whole job
    
    strategy:
      matrix:
        os: [windows-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: node/package-lock.json
          
      - name: Install dependencies
        working-directory: ./node
        run: npm ci
        timeout-minutes: 10
        
      - name: Lint Code
        working-directory: ./node
        run: npm run lint
        timeout-minutes: 5

      - name: Run Unit Tests
        working-directory: ./node
        run: npm run test:unit
        timeout-minutes: 10
        
      - name: Build Vite Application
        working-directory: ./node
        env:
          VITE_APP_MDP: ${{ secrets.VITE_APP_MDP }}
          VITE_REPLICACHE_LICENSE_KEY : ${{ secrets.VITE_REPLICACHE_LICENSE_KEY }}
        run: npm run build:safe
        timeout-minutes: 10
        
      - name: Verify Build Output
        working-directory: ./node
        run: |
          echo "Build completed, verifying 'dist' directory..."
          ls -R dist/ || dir /s dist\
          echo "Verification successful."
        timeout-minutes: 2

      - name: Publish to GitHub
        working-directory: ./node
        run: npx electron-forge publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 10