name: Release Electron App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45 # Generous timeout for the whole job
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: node/package-lock.json
          
      - name: Install dependencies
        working-directory: ./node
        run: npm ci
        timeout-minutes: 10
        
      # Step 1: Build the Vite app using your safe script
      - name: Build Vite Application (Safe)
        working-directory: ./node
        run: npm run build:safe
        timeout-minutes: 10
        
      # Step 2: Verify the build output exists
      - name: Verify Build Output
        working-directory: ./node
        run: |
          echo "Build completed, verifying 'dist' directory..."
          ls -R dist/ || dir /s dist\
          echo "Verification successful."
        timeout-minutes: 2

      # Step 3: Package the app (creates the platform-specific folder in 'out')
      - name: Package Application
        working-directory: ./node
        run: npx electron-forge package
        timeout-minutes: 10

      # Step 4: Make the distributables (creates installers/zips in 'out/make')
      - name: Make Distributables
        working-directory: ./node
        run: npx electron-forge make
        timeout-minutes: 15

      # Step 5: Publish the created artifacts to GitHub Releases
      - name: Publish to GitHub
        working-directory: ./node
        run: npx electron-forge publish --skip-package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 10