name: Release Electron App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: node/package-lock.json
          
      - name: Install dependencies
        working-directory: ./node
        run: npm ci
        
      - name: Build application (Windows)
        if: runner.os == 'Windows'
        working-directory: ./node
        shell: cmd
        run: |
          set CI=false
          set NODE_ENV=production
          set ELECTRON=true
          npm run build
          
      - name: Build application (Unix)
        if: runner.os != 'Windows'
        working-directory: ./node
        run: npm run build
        env:
          CI: false
          NODE_ENV: production
          ELECTRON: true
          
      - name: Verify build output
        working-directory: ./node
        run: |
          echo "Build completed, checking output..."
          ls dist/ || dir dist\
          
      - name: Publish to GitHub
        working-directory: ./node
        run: npx electron-forge publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ENV: production